name: parahumans
version: 0.0.1
description: An openworld interactive fiction based in the world of Worm by Wildbow.
author: Daniel Einspanjer <deinspanjer@gmail.com>
homepage: https://www.yipyip.com
publish_to: none

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  built_collection: ^5.1.0
  built_value: ^8.1.1
  cli_menu: ^0.3.0-nullsafety.0
  edgehead:
    path: ../edgehead
  egamebook_builder:
    path: ../egamebook_builder
  logging: ^1.0.1
  meta: ^1.7.0
  path: ^1.8.0
  quiver: ^3.0.1
  slot_machine: ^5.0.1

dev_dependencies:
  args: ^2.1.1
  build_runner: ^2.0.6
  built_value_generator: ^8.1.1
  lint: ^1.5.3
  t_stats: ^3.0.0
  test: ^1.17.9
