name: egamebook_builder
description: Builders for egamebook.
version: 1.0.0

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  analyzer: '>=1.7.0 <2.0.0'
  build: ^2.0.3
  code_builder: ^4.0.0
  dart_style: ^2.0.1
  glob: ^2.0.1
  source_gen: ^1.0.2

dev_dependencies:
  meta: ^1.7.0
  test: ^1.15.3